spring.application.name=melody-backend

server.port=8080

# =====================================================
# SQL SERVER
# =====================================================

# SQL SERVER
spring.datasource.url=jdbc:sqlserver://LEO:1433;databaseName=MelodyDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=melody_app
spring.datasource.password=MelodyApp@2026Secure!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# =====================================================
# JWT
# =====================================================

melody.jwt.secret=MelodySuperSecretKeyForJwtAuthentication2026VeryLongSecretKey
melody.jwt.expiration=86400000

# =====================================================
# SQL INITIALIZATION
# =====================================================

spring.sql.init.mode=never